/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.destakcar.telas;

/**
 *
 * @author Igor Pierine Santos
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCleinteCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCleinteCep = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCleinteNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCleinteTel = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        cboCleinteUf = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtClienteEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtClienteNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCleinteDNS = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtClienteCompl = new javax.swing.JTextField();
        txtCleinteCPF = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCleinteBairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCleinteEndereco = new javax.swing.JTextField();
        btnEditarCli = new javax.swing.JButton();
        btnAdicionarCli = new javax.swing.JButton();
        btnConsultarCli = new javax.swing.JButton();
        btnExcluirCli = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        setMinimumSize(new java.awt.Dimension(124, 34));
        setNormalBounds(new java.awt.Rectangle(0, 0, 124, 0));
        setPreferredSize(new java.awt.Dimension(550, 480));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 20, 17);

        txtCleinteCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCleinteCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteCidade);
        txtCleinteCidade.setBounds(360, 290, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("UF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 300, 20, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("E-mail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 340, 50, 17);

        try {
            txtCleinteCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCleinteCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteCepActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteCep);
        txtCleinteCep.setBounds(80, 290, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Data Nasc.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 140, 80, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nome");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 50, 17);

        txtCleinteNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCleinteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteNome);
        txtCleinteNome.setBounds(80, 170, 450, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CPF");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 140, 30, 17);

        try {
            txtCleinteTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)  ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCleinteTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteTelActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteTel);
        txtCleinteTel.setBounds(80, 330, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CEP");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 300, 30, 17);

        txtClienteId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClienteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtClienteId);
        txtClienteId.setBounds(80, 130, 70, 30);

        cboCleinteUf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboCleinteUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(cboCleinteUf);
        cboCleinteUf.setBounds(250, 290, 50, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Compl");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 260, 50, 17);

        txtClienteEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtClienteEmail);
        txtClienteEmail.setBounds(310, 330, 220, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Numero");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 220, 56, 17);

        txtClienteNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClienteNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtClienteNumero);
        txtClienteNumero.setBounds(400, 210, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Cidade");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 300, 50, 17);

        try {
            txtCleinteDNS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCleinteDNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteDNSActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteDNS);
        txtCleinteDNS.setBounds(240, 130, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Telefone");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 340, 59, 17);

        txtClienteCompl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClienteCompl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteComplActionPerformed(evt);
            }
        });
        getContentPane().add(txtClienteCompl);
        txtClienteCompl.setBounds(80, 250, 240, 30);

        try {
            txtCleinteCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCleinteCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteCPFActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteCPF);
        txtCleinteCPF.setBounds(390, 130, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Bairro");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 260, 50, 17);

        txtCleinteBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCleinteBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteBairroActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteBairro);
        txtCleinteBairro.setBounds(400, 250, 130, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Endereço");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 220, 70, 17);

        txtCleinteEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCleinteEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCleinteEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCleinteEndereco);
        txtCleinteEndereco.setBounds(80, 210, 240, 30);

        btnEditarCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditarCli.setForeground(new java.awt.Color(0, 102, 255));
        btnEditarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/user_edit.png"))); // NOI18N
        btnEditarCli.setText("Editar");
        btnEditarCli.setToolTipText("Editar");
        btnEditarCli.setBorder(null);
        btnEditarCli.setBorderPainted(false);
        btnEditarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarCli.setPreferredSize(new java.awt.Dimension(20, 40));
        getContentPane().add(btnEditarCli);
        btnEditarCli.setBounds(290, 390, 100, 30);

        btnAdicionarCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdicionarCli.setForeground(new java.awt.Color(0, 102, 255));
        btnAdicionarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/accept.png"))); // NOI18N
        btnAdicionarCli.setText("Confirmar");
        btnAdicionarCli.setToolTipText("Adicionar");
        btnAdicionarCli.setBorder(null);
        btnAdicionarCli.setBorderPainted(false);
        btnAdicionarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdicionarCli.setPreferredSize(new java.awt.Dimension(20, 40));
        btnAdicionarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarCli);
        btnAdicionarCli.setBounds(70, 390, 100, 30);

        btnConsultarCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarCli.setForeground(new java.awt.Color(0, 102, 255));
        btnConsultarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/magnifier.png"))); // NOI18N
        btnConsultarCli.setText("Buscar");
        btnConsultarCli.setToolTipText("Consultar");
        btnConsultarCli.setBorder(null);
        btnConsultarCli.setBorderPainted(false);
        btnConsultarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConsultarCli.setPreferredSize(new java.awt.Dimension(20, 40));
        btnConsultarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarCli);
        btnConsultarCli.setBounds(180, 390, 100, 30);

        btnExcluirCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluirCli.setForeground(new java.awt.Color(0, 102, 255));
        btnExcluirCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/user_delete.png"))); // NOI18N
        btnExcluirCli.setText("Deletar");
        btnExcluirCli.setToolTipText("Excluir");
        btnExcluirCli.setBorder(null);
        btnExcluirCli.setBorderPainted(false);
        btnExcluirCli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExcluirCli.setPreferredSize(new java.awt.Dimension(20, 40));
        btnExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirCli);
        btnExcluirCli.setBounds(400, 390, 100, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/icone-cliente.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 10, 230, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCleinteCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteCidadeActionPerformed

    private void txtCleinteCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteCepActionPerformed

    private void txtCleinteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteNomeActionPerformed

    private void txtCleinteTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteTelActionPerformed

    private void txtClienteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteIdActionPerformed

    private void txtClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteEmailActionPerformed

    private void txtClienteNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteNumeroActionPerformed

    private void txtCleinteDNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteDNSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteDNSActionPerformed

    private void txtClienteComplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteComplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteComplActionPerformed

    private void txtCleinteCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteCPFActionPerformed

    private void txtCleinteBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteBairroActionPerformed

    private void txtCleinteEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCleinteEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCleinteEnderecoActionPerformed

    private void btnAdicionarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCliActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAdicionarCliActionPerformed

    private void btnConsultarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCliActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnConsultarCliActionPerformed

    private void btnExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCli;
    private javax.swing.JButton btnConsultarCli;
    private javax.swing.JButton btnEditarCli;
    private javax.swing.JButton btnExcluirCli;
    private javax.swing.JComboBox<String> cboCleinteUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCleinteBairro;
    private javax.swing.JFormattedTextField txtCleinteCPF;
    private javax.swing.JFormattedTextField txtCleinteCep;
    private javax.swing.JTextField txtCleinteCidade;
    private javax.swing.JFormattedTextField txtCleinteDNS;
    private javax.swing.JTextField txtCleinteEndereco;
    private javax.swing.JTextField txtCleinteNome;
    private javax.swing.JFormattedTextField txtCleinteTel;
    private javax.swing.JTextField txtClienteCompl;
    private javax.swing.JTextField txtClienteEmail;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtClienteNumero;
    // End of variables declaration//GEN-END:variables
}
