/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.destakcar.telas;

import java.sql.*;
import br.com.destakcar.dal.ModuloConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas.goncalves
 */
public class TelaLogin extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        String sql = "select * from tbusers where login=? and senha=?";
        try {
            // Prepara a consulta ao banco em função a caixa de texto cada ? será substituido

            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUser.getText());
            pst.setString(2, txtPassword.getText());

            // A linha abaixo executa a query
            rs = pst.executeQuery();
            if (rs.next()) {
                // Se existir user e senha correspondente
                // Pega o perfil do usuário no banco
                String perfil = rs.getString(6);
                // System.out.println(perfil);
                if (perfil.equals("admin")) {
                    // Se ele for admin terá acesso total ao sistema
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.menuUsuario.setEnabled(true);
                    this.dispose();

                } else {
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    this.dispose();
                }
                TelaPrincipal.lblUsuario.setText(rs.getString(2));
                TelaPrincipal.lblPerfil.setText(rs.getString(6));
                conexao.close();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválido");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.conector();

        // Testando a conexão com o banco mudando o status na tela
        if (conexao != null) {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/carro.png")));
        } else {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/batida.png")));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        lblPassword = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Destak Car Login");
        setBackground(new java.awt.Color(0, 153, 255));
        setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        lblPassword.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblPassword.setText("Senha");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(130, 270, 100, 29);

        txtUser.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        getContentPane().add(txtUser);
        txtUser.setBounds(230, 180, 270, 50);

        lblUser.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblUser.setText("Usuário");
        getContentPane().add(lblUser);
        lblUser.setBounds(120, 190, 100, 30);

        txtPassword.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        getContentPane().add(txtPassword);
        txtPassword.setBounds(230, 250, 270, 50);

        btnLogin.setBackground(new java.awt.Color(11, 58, 96));
        btnLogin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Acessar");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(230, 330, 160, 50);

        panel1.setBackground(new java.awt.Color(11, 58, 96));
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Destak Car");
        panel1.add(jLabel1);
        jLabel1.setBounds(240, 20, 210, 50);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/batida.png"))); // NOI18N
        panel1.add(lblStatus);
        lblStatus.setBounds(560, 20, 80, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/logo1.png"))); // NOI18N
        panel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 80, 70);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 670, 100);

        setSize(new java.awt.Dimension(686, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUser;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
