/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.destakcar.telas;

import java.sql.*;
import br.com.destakcar.dal.ModuloConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor Pierine Santos
 */
public class TelaPagamentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCarro
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaPagamentos() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void consultar() {
        String sql = "select * from tbcliente where cpfcli=?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPagamentoCPF.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtPagamentoId.setText(rs.getString(1));
                txtPagamentoNome.setText(rs.getString(4));
            } else {
                JOptionPane.showMessageDialog(null, "Cliente não encontrado");
                // Limpando os campos
                txtPagamentoCPF.setText(null);
                txtPagamentoTotal.setText(null);
                txtPagamentoId.setText(null);

            }
        } catch (SQLException e) {
            jOptionPane.showMessageDialog(null, e);
        }
    }

    private void buscarServico() {
        String sql = "select * from tbos where idcli=?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPagamentoId.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                cboPagamentoMarca.setSelectedItem(rs.getString(2));
                txtPagamentoModelo.setText(rs.getString(3));
                cboPagamentoAno.setSelectedItem(rs.getString(4));
                txtPagamentoPlaca.setText(rs.getString(5));
                txtareaPagamento.setText(rs.getString(6));

            } else {
                JOptionPane.showMessageDialog(null, "Serviço não encontrado");
                // Limpando os campos

            }
        } catch (SQLException e) {
            jOptionPane.showMessageDialog(null, e);
        }
    }

    private void finalizar() {
        int confirma;
        confirma = JOptionPane.showConfirmDialog(null, "Deseja finalizar este serviço?", "Total a pagar " + txtPagamentoTotal.getText(), JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "update tbos set statuspg=?, valorpg=? where idcli = ?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, cboPagamentoStatus.getSelectedItem().toString());
                pst.setString(2, txtPagamentoTotal.getText());
                pst.setString(3, txtPagamentoId.getText());
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Finalizado com sucesso!");
                txtPagamentoPlaca.setText(null);
                txtPagamentoModelo.setText(null);
                txtPagamentoNome.setText(null);
                txtareaPagamento.setText(null);
                txtPagamentoCPF.setText(null);
                txtPagamentoId.setText(null);
                txtPagamentoTotal.setText(null);
                cboPagamentoStatus.setSelectedItem(null);
                cboPagamentoMarca.setSelectedItem(null);
                cboPagamentoAno.setSelectedItem(null);
            } catch (SQLException e) {
                jOptionPane.showMessageDialog(null, e);
            }
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPagamentoPlaca = new javax.swing.JTextField();
        btnFinalizarPag = new javax.swing.JButton();
        btnConsultarPag = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPagamentoCPF = new javax.swing.JFormattedTextField();
        cboPagamentoMarca = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cboPagamentoStatus = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaPagamento = new javax.swing.JTextArea();
        txtPagamentoId = new javax.swing.JTextField();
        txtPagamentoModelo = new javax.swing.JTextField();
        btnBuscarPagamento = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtPagamentoNome = new javax.swing.JTextField();
        txtPagamentoTotal = new javax.swing.JTextField();
        cboPagamentoAno = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pagamento");
        setPreferredSize(new java.awt.Dimension(550, 480));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Marca");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Serviço");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 70, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Modelo");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(260, 180, 60, 30);

        txtPagamentoPlaca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPagamentoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPagamentoPlaca);
        txtPagamentoPlaca.setBounds(330, 220, 190, 30);

        btnFinalizarPag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFinalizarPag.setForeground(new java.awt.Color(0, 102, 255));
        btnFinalizarPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/accept.png"))); // NOI18N
        btnFinalizarPag.setText("Finalizar");
        btnFinalizarPag.setToolTipText("Adicionar");
        btnFinalizarPag.setBorder(null);
        btnFinalizarPag.setBorderPainted(false);
        btnFinalizarPag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFinalizarPag.setPreferredSize(new java.awt.Dimension(20, 40));
        btnFinalizarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPagActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarPag);
        btnFinalizarPag.setBounds(310, 380, 120, 30);

        btnConsultarPag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarPag.setForeground(new java.awt.Color(0, 102, 255));
        btnConsultarPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/magnifier.png"))); // NOI18N
        btnConsultarPag.setToolTipText("Consultar");
        btnConsultarPag.setBorder(null);
        btnConsultarPag.setBorderPainted(false);
        btnConsultarPag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConsultarPag.setPreferredSize(new java.awt.Dimension(20, 40));
        btnConsultarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPagActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarPag);
        btnConsultarPag.setBounds(90, 140, 40, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/Dolar.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(190, 0, 190, 130);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("CPF");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 140, 50, 30);

        try {
            txtPagamentoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPagamentoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoCPFActionPerformed(evt);
            }
        });
        getContentPane().add(txtPagamentoCPF);
        txtPagamentoCPF.setBounds(140, 140, 130, 30);

        cboPagamentoMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboPagamentoMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecionar-", "FIAT", "Volkswagen", "GM", "Hyundai", "Jeep", "Renault", "Toyota", "Ford", "Honda", "Nissan", "Caoa Chery", "Peugeot", "Mitsubishi", "Citroen", "BMW", "Volvo", "Mercedes", "Audi", "Kia", "RAM", "Iveco", "Land Rover", "Porsche", "Suzuki", "Mini", "JAC", "Troler", "Subaru", "Jaguar", "Dodge", "Foton", "Lexus", " " }));
        cboPagamentoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPagamentoMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(cboPagamentoMarca);
        cboPagamentoMarca.setBounds(90, 180, 140, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(" Ano");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 220, 50, 30);

        cboPagamentoStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboPagamentoStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Pago", "Pendente" }));
        cboPagamentoStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPagamentoStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cboPagamentoStatus);
        cboPagamentoStatus.setBounds(400, 330, 120, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Status");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(330, 330, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Placa");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 220, 50, 30);

        txtareaPagamento.setColumns(20);
        txtareaPagamento.setRows(5);
        jScrollPane1.setViewportView(txtareaPagamento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 260, 430, 60);

        txtPagamentoId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPagamentoId.setDoubleBuffered(true);
        txtPagamentoId.setEnabled(false);
        txtPagamentoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtPagamentoId);
        txtPagamentoId.setBounds(480, 140, 40, 30);

        txtPagamentoModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPagamentoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtPagamentoModelo);
        txtPagamentoModelo.setBounds(330, 180, 190, 30);

        btnBuscarPagamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarPagamento.setForeground(new java.awt.Color(0, 102, 255));
        btnBuscarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/destakcar/icones/magnifier.png"))); // NOI18N
        btnBuscarPagamento.setText("Buscar");
        btnBuscarPagamento.setToolTipText("Editar");
        btnBuscarPagamento.setBorder(null);
        btnBuscarPagamento.setBorderPainted(false);
        btnBuscarPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarPagamento.setPreferredSize(new java.awt.Dimension(20, 40));
        btnBuscarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarPagamento);
        btnBuscarPagamento.setBounds(180, 380, 110, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText(" Nome");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(270, 140, 50, 30);

        txtPagamentoNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPagamentoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtPagamentoNome);
        txtPagamentoNome.setBounds(330, 140, 150, 30);

        txtPagamentoTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPagamentoTotal.setText("R$");
        txtPagamentoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtPagamentoTotal);
        txtPagamentoTotal.setBounds(120, 330, 150, 30);

        cboPagamentoAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboPagamentoAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecionar-", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "", "" }));
        cboPagamentoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPagamentoAnoActionPerformed(evt);
            }
        });
        getContentPane().add(cboPagamentoAno);
        cboPagamentoAno.setBounds(90, 220, 120, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Total a Pagar");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 330, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagamentoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagamentoPlacaActionPerformed

    private void btnFinalizarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPagActionPerformed
        // TODO add your handling code here:
        finalizar();
    }//GEN-LAST:event_btnFinalizarPagActionPerformed

    private void btnConsultarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPagActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_btnConsultarPagActionPerformed

    private void txtPagamentoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagamentoCPFActionPerformed

    private void cboPagamentoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPagamentoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPagamentoMarcaActionPerformed

    private void cboPagamentoStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPagamentoStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPagamentoStatusActionPerformed

    private void txtPagamentoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagamentoIdActionPerformed

    private void txtPagamentoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagamentoModeloActionPerformed

    private void btnBuscarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPagamentoActionPerformed
        // TODO add your handling code here:
        buscarServico();
    }//GEN-LAST:event_btnBuscarPagamentoActionPerformed

    private void txtPagamentoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagamentoNomeActionPerformed

    private void txtPagamentoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagamentoTotalActionPerformed

    private void cboPagamentoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPagamentoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPagamentoAnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPagamento;
    private javax.swing.JButton btnConsultarPag;
    private javax.swing.JButton btnFinalizarPag;
    private javax.swing.JComboBox<String> cboPagamentoAno;
    private javax.swing.JComboBox<String> cboPagamentoMarca;
    private javax.swing.JComboBox<String> cboPagamentoStatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtPagamentoCPF;
    private javax.swing.JTextField txtPagamentoId;
    private javax.swing.JTextField txtPagamentoModelo;
    private javax.swing.JTextField txtPagamentoNome;
    private javax.swing.JTextField txtPagamentoPlaca;
    private javax.swing.JTextField txtPagamentoTotal;
    private javax.swing.JTextArea txtareaPagamento;
    // End of variables declaration//GEN-END:variables
}
